#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"

if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

if [ -d "$TheSkyX_Path/PlugIns" ]; then
	PLUGINS_DIR="$TheSkyX_Path/PlugIns"
elif [ -d "$TheSkyX_Path/Resources/Common/PlugIns64" ]; then
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns64"
else
	PLUGINS_DIR="$TheSkyX_Path/Resources/Common/PlugIns"
fi

echo "Installing in $PLUGINS_DIR/PowerControlPlugIns/"

mkdir -p "$PLUGINS_DIR/PowerControlPlugIns"

cp "/tmp/DragonflyPower_X2/powercontrollist DragonflyPower.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/PowerControlPlugIns/DragonflyPower.ui"
cp "/tmp/DragonflyPower_X2/DragonflyPower.ui" "$PLUGINS_DIR/PowerControlPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/PowerControlPlugIns/Lunatico3.png"
cp "/tmp/DragonflyPower_X2/Lunatico3.png" "$PLUGINS_DIR/PowerControlPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

rm -f "$PLUGINS_DIR/PowerControlPlugIns/libDragonflyPower.dylib"
cp "/tmp/DragonflyPower_X2/libDragonflyPower.dylib" "$PLUGINS_DIR/PowerControlPlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/powercontrollist DragonflyPower.txt"
	chown $app_owner "$PLUGINS_DIR/PowerControlPlugIns/DragonflyPower.ui"
	chown $app_owner "$PLUGINS_DIR/PowerControlPlugIns/Lunatico3.png"
	chown $app_owner "$PLUGINS_DIR/PowerControlPlugIns/libDragonflyPower.dylib"
fi

rm -rf /tmp/DragonflyPower_X2

